### ISSUE TITLE
Compile application

### ISSUE THREAD

**Issue by koriym** [bearsunday/BEAR.Package#125]
`bin/compiler` compile application and output `class files` and cache before deploy.
- a preloader file (combined class file)
- AOP class files (generated class files)
- object graph for application and resource objects (cache)
- annotations (cache)

Application compile output cache as cache files and APCu dump file.
Also you can make sure **All dependency are injectable and all annotations are readable** without run.

```
$ bin/bear.compile apps/Demo.Sandbox
compile loader ...
php /Users/akihito/git/BEAR.Package/vendor/bin/classpreloader.php compile --strip_comments=0 --config=apps/Demo.Sandbox/var/lib/preloader/config.php --output=apps/Demo.Sandbox/var/tmp/preloader/preload.php
> Loading configuration file
- Found 1 files
> Compiling classes
- Writing /Users/akihito/git/BEAR.Package/src/Bootstrap/Bootstrap.php
- Writing /Users/akihito/git/BEAR.Package/vendor/ray/di/src/ProviderInterface.php
... 略
- Writing /Users/akihito/git/BEAR.Package/src/Provide/ResourceView/HalFactory.php
> Compiled loader written to apps/Demo.Sandbox/var/tmp/preloader/preload.php
- 366 kb
php -l apps/Demo.Sandbox/var/tmp/preloader/preload.php

page://self/blog/posts/pager -> Demo\Sandbox\Resource\Page\Blog\Posts\Pager
page://self/blog/posts/post -> Demo_Sandbox_Resource_Page_Blog_Posts_Post_c0be75b7e2054a1c4fc1b95a68e11d5cRayAop
page://self/blog/posts -> Demo_Sandbox_Resource_Page_Blog_Posts_c0be75b7e2054a1c4fc1b95a68e11d5cRay...
app://self/restbucks/payment36 resources created.
compile annotations ...
BEAR\Resource\ResourceObject::setRenderer -> @Ray\Di\Di\Inject
Demo\Sandbox\Resource\Page\Blog\Posts\Pager::setResource -> @Ray\Di\Di\Inject
Demo\Sandbox\Resource\Page\Blog\Posts\Post::onGet -> @BEAR\Sunday\Annotation\Cache
```

**Comment by koriym** [comment]
by  https://github.com/koriym/BEAR.Package/commit/a6944d953525e5f031d09642dce57234f49d851d and https://github.com/koriym/BEAR.Package/commit/b4e2c23327f82df82ee8a65568c023d6937ed3d9

**Comment by kenjis** [comment]
I've got two fatal errors.

```
$ composer create-project bear/package ./bear
$ cd bear
$ bin/bear.compile apps/Demo.Sandbox
compile loader ...
php /Users/kenji/tmp/bear/vendor/bin/classpreloader.php compile --strip_comments=0 --config=apps/Demo.Sandbox/var/lib/preloader/config.php --output=apps/Demo.Sandbox/var/tmp/preloader/preload.php
> Loading configuration file
...
> Compiled loader written to apps/Demo.Sandbox/var/tmp/preloader/preload.php
- 413 kb
php -l apps/Demo.Sandbox/var/tmp/preloader/preload.php

Fatal error: Cannot mix bracketed namespace declarations with unbracketed namespace declarations in apps/Demo.Sandbox/var/tmp/preloader/preload.php on line 12755
Errors parsing apps/Demo.Sandbox/var/tmp/preloader/preload.php
compile resources ...
...
page://self/hello/world -> Demo\Sandbox\Resource\Page\Hello\World
page://self/index -> Demo\Sandbox\Resource\Page\Index

Fatal error: Uncaught exception 'Ray\Di\Exception\NotBound' with message 'typehint='BEAR\Resource\LoggerInterface', annotate='*' for $logger in class 'Demo\Sandbox\Resource\Page\Restbucks\Index'' in /Users/kenji/tmp/bear/vendor/ray/di/src/Binder.php:293
Stack trace:
#0 /Users/kenji/tmp/bear/vendor/ray/di/src/Binder.php(224): Ray\Di\Binder->getNotBoundException(Array, 0, 'BEAR\Resource\L...', '*')
#1 /Users/kenji/tmp/bear/vendor/ray/di/src/Binder.php(112): Ray\Di\Binder->jitBinding(Array, 'BEAR\Resource\L...', '*', 0)
#2 /Users/kenji/tmp/bear/vendor/ray/di/src/Binder.php(94): Ray\Di\Binder->getNoBoundParam(Array, 0)
#3 /Users/kenji/tmp/bear/vendor/ray/di/src/Binder.php(72): Ray\Di\Binder->extractParam(Array, 0)
#4 /Users/kenji/tmp/bear/vendor/ray/di/src/BoundInstance.php(371): Ray\Di\Binder->bindMethod(Object(Demo\Sandbox\Module\AppModule), 'Demo\Sandbox\Re...', Array)
#5 /Users/kenji/tmp/bear/vendor/ray/di/src/BoundInstance.php(352): Ray\Di\BoundInstance->getSetter(Array)
#6 /Users/kenji/tmp/bear/vendor/ray/di/src/BoundIn in /Users/kenji/tmp/bear/vendor/ray/di/src/Binder.php on line 293
```

**Comment by kenjis** [comment]
The first Fatal error is gone when I run the command again.

**Comment by koriym** [comment]
"Cannot mix bracketed namespace declarations", this error is triggered due to the bug of preloader.

I once fix the bug in my forked repo. But found someone try to fix in better way and mine doesn't work anymore due to ... forgot anyway external reason. See more at https://github.com/mtdowling/ClassPreloader/pull/13

There seems to be two solutions.
- 1) fix preloader or wait preloader fixed
- 2) update preloader config to run (exclude non-namespeced class like Smarty or maybe also Twig)
