### ISSUE TITLE
Tutorial error without APCu

### ISSUE THREAD

**Issue by pazworld** [bearsunday/BEAR.Package#406]
### Bug Report

CacheException occures when run tutorial without APCu.

```
$ php bin/app.php get /weekday
PHP Fatal error:  Uncaught Symfony\Component\Cache\Exception\CacheException: APCu is not enabled. in /workspaces/MyVendor.Weekday/MyVendor.Weekday/vendor/symfony/cache/Adapter/ApcuAdapter.php:31
Stack trace:
#0 /workspaces/MyVendor.Weekday/MyVendor.Weekday/vendor/bear/package/src/Injector.php(34): Symfony\Component\Cache\Adapter\ApcuAdapter->__construct('_workspaces_MyV...')
#1 /workspaces/MyVendor.Weekday/MyVendor.Weekday/src/Injector.php(27): BEAR\Package\Injector::getInstance('MyVendor\\Weekda...', 'cli-hal-api-app', '/workspaces/MyV...')
#2 /workspaces/MyVendor.Weekday/MyVendor.Weekday/src/Bootstrap.php(31): MyVendor\Weekday\Injector::getInstance('cli-hal-api-app')
#3 /workspaces/MyVendor.Weekday/MyVendor.Weekday/bin/app.php(8): MyVendor\Weekday\Bootstrap->__invoke('cli-hal-api-app', Array, Array)
#4 {main}
  thrown in /workspaces/MyVendor.Weekday/MyVendor.Weekday/vendor/symfony/cache/Adapter/ApcuAdapter.php on line 31

Fatal error: Uncaught Symfony\Component\Cache\Exception\CacheException: APCu is not enabled. in /workspaces/MyVendor.Weekday/MyVendor.Weekday/vendor/symfony/cache/Adapter/ApcuAdapter.php:31
Stack trace:
#0 /workspaces/MyVendor.Weekday/MyVendor.Weekday/vendor/bear/package/src/Injector.php(34): Symfony\Component\Cache\Adapter\ApcuAdapter->__construct('_workspaces_MyV...')
#1 /workspaces/MyVendor.Weekday/MyVendor.Weekday/src/Injector.php(27): BEAR\Package\Injector::getInstance('MyVendor\\Weekda...', 'cli-hal-api-app', '/workspaces/MyV...')
#2 /workspaces/MyVendor.Weekday/MyVendor.Weekday/src/Bootstrap.php(31): MyVendor\Weekday\Injector::getInstance('cli-hal-api-app')
#3 /workspaces/MyVendor.Weekday/MyVendor.Weekday/bin/app.php(8): MyVendor\Weekday\Bootstrap->__invoke('cli-hal-api-app', Array, Array)
#4 {main}
  thrown in /workspaces/MyVendor.Weekday/MyVendor.Weekday/vendor/symfony/cache/Adapter/ApcuAdapter.php on line 31
```

### How to reproduce

Run tutorial without apc. I use docker container `php:cli-buster` and `php:8-alpine`

**Comment by koriym** [comment]
https://github.com/symfony/cache/blob/e855b4b25324819fb1e92bcf5974aba362dc0e36/Adapter/ApcuAdapter.php#L52

これがfalseを返して例外が投げられているようです。

```
\ini_get('apc.enabled')
```

これはBEARのAPCポリフィルで`ini_set`してもtrueにならないのが分かりました。
Symfonyのポリフィルを使っても有効になりません。（困りました）

**Comment by koriym** [comment]
https://github.com/bearsunday/BEAR.Package/releases/tag/1.14.4

このリリースで修正完了しました！

**Comment by pazworld** [comment]
新しいバージョンで動作することを確認しました。早々にご対応くださいましてありがとうございました。

**Comment by koriym** [comment]
@pazworld 報告ありがとうございます。 APCuのポリフィルを廃止して、常にSymfonyのAPCuがサポートされているかどうかを基準にしたので今後Symfonyの実装が変わったとしてもこのような問題は起こらないと思います。

これからもよろしくお願いします！
